services:
  react-app:
    image: react-app:development
    build: 
      context: .
      dockerfile: Dockerfile 
      target: ${ENVIRONMENT}
    ports:
      - "5173:5173"
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./react-app/src 
          target: /app/src
        - action: sync+restart
          path: ./react-app
          target: /app
          ignore:
            - ./src
        - action: rebuild
          path: ./react-app/package.json
          

